<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <title>SaturnoOS</title>
    
</head>
<body>
    <h1>SaturnoOS</h1>
    <p>"The new distro that listens to their users and their ideas"</p>
    <p>For contact us stay updatin everyday, the gmail will be created for if you have a question, i will put it soon :)</p>
</body>
<head>
    <body>
        <p>"SaturnoOS still in development, probably it will launch in January 2026, the webpage it will also update"</p>
        <h2>Who we are?</h2>
        <p>We (im) a new linux distribution gentoo based, is developed by an anonymus person (Im not anonymus on Reddit :)) in the future i will show who i am</p>
        <h2>Why should i use your distro?</h2>
        <p>Our (Mine) distro should be use because is not only mine, is for everybody, and every question or idea will be read, every distro listen to a small amount of persons, but me i will listen all, also it will work in the future on 32 bit, and i will try that ANY COMPUTER can run my distro without any problem, for te moment is a project because im a teenager and i have to go to the high school and more things, when i have time i will work, in my country if they heard a guy with 15 years made a linux distro they would say im the future Steve Jobs (In my City im the only Linux user, and in Spain they dont know too much about Linux) 13 years ago a 12 yeard old boy make a respin of Ubuntu called Asturix, but mine it ill be a Gentoo based OS, an real new distro </p>
        <p>When i said i will try to the distro can work on any computer is because i have an history (Its down of the page)</p>
        <h2>What are the requirement of Saturnoo?</h2>
        <p>64 bits (at the moment)</p>
        <p>2 (better 3) Gb of RAM (Also at the moment)</p>
        <p>10-15 GB of free space</p>
    </body>
    <head></head>
    <body>
        <h2>The history of Saturno</h2>
        <p> A year ago i had a samsung ativ tab 5 with Windows 10 running with an 50 gb ssd and 2 gb of RAM (Yes 2 Freaking GB) and as you can imagine it doesnt work very well, i cant have 2 chrome windows, i cant watch youtube..., so one day i said, i will install Linux, because i have a PS3 and i saw a video that you can turn it to a pc with Linux, so i tried with LMDE 6, it started but it reboot, i tried every 32 bit distro, no one worked, i was angry, i tried with Virtualbox, the same thing, one day of February (Probably one of one of my best days on my life) my mother gived to me an old laptop from her work with Windows 7 (My childhood OS) so i tried to install linux but i dont wanted to format all the disk because is a GPT and i loved windows 7, so i installed VMWare, i was happy to have a 64 bits Laptop, and in there is start to install every distro that was in my head, in May i said: Why not to create my distro, LFS give me problems, but Gentoo at the moment it doesnt, and i want that anyone doesnt have to pass what have passed to me with the Samsung laptop (I still hating it) and thats all the history</p>
<P> GITHUB: https://github.com/Saturnoos/SaturnoOS</P>

    </body>
    <head>
        <body>
           
           
           
           
           
           
           
           
           
           
           
           
           
           
           
           
           
           
           
           
           
           
           
            Saturnoo is an linux distro, the trademark Saturno/Saturnoo it cant be used for another linux distribution, is the name of OUR DISTRO, we can put a demand if it is necesary, this was wrotten 20/10/2025 at 19:32 Madrid Spain
        </body>
    </head>
</html>
